"""initial_schema

Revision ID: 7b5da8960037
Revises: 
Create Date: 2026-02-22 10:39:29.945227
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '7b5da8960037'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_periods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False, comment='Mes del periodo (1-12)'),
    sa.Column('year', sa.Integer(), nullable=False, comment='Año del periodo (ej: 2026)'),
    sa.Column('description', sa.String(length=100), nullable=False, comment="Descripción legible (ej: 'Febrero 2026')"),
    sa.Column('base_amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='Monto base de administración para este periodo'),
    sa.Column('due_date', sa.Date(), nullable=False, comment='Fecha límite de pago'),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'CANCELLED', name='period_status', create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month', 'year', name='uq_period_month_year')
    )
    op.create_table('owners',
    sa.Column('id', sa.UUID(), nullable=False, comment='Identificador único del propietario'),
    sa.Column('auth_user_id', sa.UUID(), nullable=True, comment='ID del usuario en Supabase Auth (opcional)'),
    sa.Column('full_name', sa.String(length=200), nullable=False, comment='Nombre completo del propietario'),
    sa.Column('id_type', sa.String(length=20), nullable=False, comment='Tipo de documento: CC, CE, NIT, Pasaporte'),
    sa.Column('id_number', sa.String(length=30), nullable=False, comment='Número de documento de identidad'),
    sa.Column('email', sa.String(length=254), nullable=False, comment='Correo electrónico para notificaciones'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='Teléfono (con código de país, ej: +573001234567)'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Notas internas sobre el propietario'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Si el propietario está activo en el sistema'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_owners_auth_user_id'), 'owners', ['auth_user_id'], unique=True)
    op.create_index(op.f('ix_owners_email'), 'owners', ['email'], unique=False)
    op.create_index(op.f('ix_owners_id_number'), 'owners', ['id_number'], unique=True)
    op.create_table('properties',
    sa.Column('id', sa.UUID(), nullable=False, comment='Identificador único del inmueble'),
    sa.Column('house_number', sa.String(length=20), nullable=False, comment="Número de la casa (ej: '1', '2A', '15')"),
    sa.Column('address', sa.String(length=300), nullable=True, comment='Dirección completa del inmueble (opcional)'),
    sa.Column('area_m2', sa.Numeric(precision=10, scale=2), nullable=True, comment='Área del inmueble en metros cuadrados'),
    sa.Column('aliquot', sa.Numeric(precision=6, scale=4), nullable=True, comment='Porcentaje de participación (alícuota) sobre áreas comunes'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Notas internas sobre la propiedad'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Si el inmueble está activo en el sistema de cobros'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_house_number'), 'properties', ['house_number'], unique=True)
    op.create_table('bills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bill_number', sa.String(length=30), nullable=False, comment='Número consecutivo de factura (ej: VDR-2026-02-001)'),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('billing_period_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False, comment='Propietario al que se dirige este cobro'),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='Monto total del cobro (suma de items)'),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'PAID', 'OVERDUE', 'CANCELLED', name='bill_status', create_constraint=True), nullable=False),
    sa.Column('pdf_url', sa.String(length=500), nullable=True, comment='URL del PDF generado (Supabase Storage o local)'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Notas internas sobre la factura'),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True, comment='Fecha/hora en que se envió la notificación'),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True, comment='Fecha/hora en que se registró el pago'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['billing_period_id'], ['billing_periods.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'billing_period_id', name='uq_bill_property_period')
    )
    op.create_index(op.f('ix_bills_bill_number'), 'bills', ['bill_number'], unique=True)
    op.create_index(op.f('ix_bills_billing_period_id'), 'bills', ['billing_period_id'], unique=False)
    op.create_index(op.f('ix_bills_owner_id'), 'bills', ['owner_id'], unique=False)
    op.create_index(op.f('ix_bills_property_id'), 'bills', ['property_id'], unique=False)
    op.create_table('property_owners',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False, comment='Si es el propietario principal (recibe los cobros)'),
    sa.Column('start_date', sa.Date(), nullable=False, comment='Fecha de inicio de la relación de propiedad'),
    sa.Column('end_date', sa.Date(), nullable=True, comment='Fecha de fin (NULL = propietario actual)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'owner_id', 'start_date', name='uq_property_owner_period')
    )
    op.create_index(op.f('ix_property_owners_owner_id'), 'property_owners', ['owner_id'], unique=False)
    op.create_index(op.f('ix_property_owners_property_id'), 'property_owners', ['property_id'], unique=False)
    op.create_table('bill_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bill_id', sa.UUID(), nullable=False),
    sa.Column('concept', sa.String(length=150), nullable=False, comment="Nombre del concepto (ej: 'Administración', 'Cuota Extraordinaria')"),
    sa.Column('description', sa.Text(), nullable=True, comment='Descripción detallada del concepto'),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='Monto de este concepto'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bill_items_bill_id'), 'bill_items', ['bill_id'], unique=False)
    op.create_table('notification_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bill_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'WHATSAPP', 'TELEGRAM', 'SMS', name='notification_channel', create_constraint=True), nullable=False, comment='Canal usado: email, whatsapp, telegram, sms'),
    sa.Column('recipient', sa.String(length=254), nullable=False, comment='Dirección del destinatario (email o teléfono)'),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'DELIVERED', 'FAILED', name='notification_status', create_constraint=True), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Mensaje de error si la entrega falló'),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_logs_bill_id'), 'notification_logs', ['bill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_logs_bill_id'), table_name='notification_logs')
    op.drop_table('notification_logs')
    op.drop_index(op.f('ix_bill_items_bill_id'), table_name='bill_items')
    op.drop_table('bill_items')
    op.drop_index(op.f('ix_property_owners_property_id'), table_name='property_owners')
    op.drop_index(op.f('ix_property_owners_owner_id'), table_name='property_owners')
    op.drop_table('property_owners')
    op.drop_index(op.f('ix_bills_property_id'), table_name='bills')
    op.drop_index(op.f('ix_bills_owner_id'), table_name='bills')
    op.drop_index(op.f('ix_bills_billing_period_id'), table_name='bills')
    op.drop_index(op.f('ix_bills_bill_number'), table_name='bills')
    op.drop_table('bills')
    op.drop_index(op.f('ix_properties_house_number'), table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_owners_id_number'), table_name='owners')
    op.drop_index(op.f('ix_owners_email'), table_name='owners')
    op.drop_index(op.f('ix_owners_auth_user_id'), table_name='owners')
    op.drop_table('owners')
    op.drop_table('billing_periods')
    # ### end Alembic commands ###
