"""add_configuracion_email_table

Revision ID: 97e1821f0d5d
Revises: b2c3d4e5f6a7
Create Date: 2026-03-12 22:41:41.727881
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '97e1821f0d5d'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracion_email',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('proveedor', sa.String(length=20), nullable=False, comment='Proveedor OAuth (google)'),
    sa.Column('email_vinculado', sa.String(length=255), nullable=False, comment='Dirección de correo vinculada'),
    sa.Column('access_token_enc', sa.Text(), nullable=False, comment='Access token cifrado con Fernet'),
    sa.Column('refresh_token_enc', sa.Text(), nullable=False, comment='Refresh token cifrado con Fernet'),
    sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=True, comment='Fecha de expiración del access token'),
    sa.Column('vinculado_en', sa.DateTime(timezone=True), nullable=False, comment='Fecha en que se vinculó la cuenta'),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=False, comment='Última actualización de tokens'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_bills_bill_number', table_name='facturas')
    op.drop_index('ix_bills_billing_period_id', table_name='facturas')
    op.drop_index('ix_bills_owner_id', table_name='facturas')
    op.drop_index('ix_bills_property_id', table_name='facturas')
    op.create_index(op.f('ix_facturas_numero_factura'), 'facturas', ['numero_factura'], unique=True)
    op.create_index(op.f('ix_facturas_periodo_facturacion_id'), 'facturas', ['periodo_facturacion_id'], unique=False)
    op.create_index(op.f('ix_facturas_propiedad_id'), 'facturas', ['propiedad_id'], unique=False)
    op.create_index(op.f('ix_facturas_propietario_id'), 'facturas', ['propietario_id'], unique=False)
    op.drop_index('ix_bill_items_bill_id', table_name='items_factura')
    op.create_index(op.f('ix_items_factura_factura_id'), 'items_factura', ['factura_id'], unique=False)
    op.drop_index('ix_property_owners_owner_id', table_name='propiedad_propietarios')
    op.drop_index('ix_property_owners_property_id', table_name='propiedad_propietarios')
    op.create_index(op.f('ix_propiedad_propietarios_propiedad_id'), 'propiedad_propietarios', ['propiedad_id'], unique=False)
    op.create_index(op.f('ix_propiedad_propietarios_propietario_id'), 'propiedad_propietarios', ['propietario_id'], unique=False)
    op.drop_index('ix_properties_house_number', table_name='propiedades')
    op.create_index(op.f('ix_propiedades_numero_casa'), 'propiedades', ['numero_casa'], unique=True)
    op.alter_column('propietarios', 'correos',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=254)),
               comment='Lista de correos electrónicos para notificaciones',
               existing_nullable=False)
    op.alter_column('propietarios', 'telefonos',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=20)),
               comment='Lista de teléfonos (con código de país, ej: +573001234567)',
               existing_nullable=False)
    op.drop_index('ix_owners_auth_user_id', table_name='propietarios')
    op.drop_index('ix_owners_id_number', table_name='propietarios')
    op.create_index(op.f('ix_propietarios_id_usuario_auth'), 'propietarios', ['id_usuario_auth'], unique=True)
    op.create_index(op.f('ix_propietarios_numero_documento'), 'propietarios', ['numero_documento'], unique=True)
    op.drop_index('ix_notification_logs_bill_id', table_name='registro_notificaciones')
    op.create_index(op.f('ix_registro_notificaciones_factura_id'), 'registro_notificaciones', ['factura_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registro_notificaciones_factura_id'), table_name='registro_notificaciones')
    op.create_index('ix_notification_logs_bill_id', 'registro_notificaciones', ['factura_id'], unique=False)
    op.drop_index(op.f('ix_propietarios_numero_documento'), table_name='propietarios')
    op.drop_index(op.f('ix_propietarios_id_usuario_auth'), table_name='propietarios')
    op.create_index('ix_owners_id_number', 'propietarios', ['numero_documento'], unique=True)
    op.create_index('ix_owners_auth_user_id', 'propietarios', ['id_usuario_auth'], unique=True)
    op.alter_column('propietarios', 'telefonos',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=20)),
               comment=None,
               existing_comment='Lista de teléfonos (con código de país, ej: +573001234567)',
               existing_nullable=False)
    op.alter_column('propietarios', 'correos',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=254)),
               comment=None,
               existing_comment='Lista de correos electrónicos para notificaciones',
               existing_nullable=False)
    op.drop_index(op.f('ix_propiedades_numero_casa'), table_name='propiedades')
    op.create_index('ix_properties_house_number', 'propiedades', ['numero_casa'], unique=True)
    op.drop_index(op.f('ix_propiedad_propietarios_propietario_id'), table_name='propiedad_propietarios')
    op.drop_index(op.f('ix_propiedad_propietarios_propiedad_id'), table_name='propiedad_propietarios')
    op.create_index('ix_property_owners_property_id', 'propiedad_propietarios', ['propiedad_id'], unique=False)
    op.create_index('ix_property_owners_owner_id', 'propiedad_propietarios', ['propietario_id'], unique=False)
    op.drop_index(op.f('ix_items_factura_factura_id'), table_name='items_factura')
    op.create_index('ix_bill_items_bill_id', 'items_factura', ['factura_id'], unique=False)
    op.drop_index(op.f('ix_facturas_propietario_id'), table_name='facturas')
    op.drop_index(op.f('ix_facturas_propiedad_id'), table_name='facturas')
    op.drop_index(op.f('ix_facturas_periodo_facturacion_id'), table_name='facturas')
    op.drop_index(op.f('ix_facturas_numero_factura'), table_name='facturas')
    op.create_index('ix_bills_property_id', 'facturas', ['propiedad_id'], unique=False)
    op.create_index('ix_bills_owner_id', 'facturas', ['propietario_id'], unique=False)
    op.create_index('ix_bills_billing_period_id', 'facturas', ['periodo_facturacion_id'], unique=False)
    op.create_index('ix_bills_bill_number', 'facturas', ['numero_factura'], unique=True)
    op.drop_table('configuracion_email')
    # ### end Alembic commands ###
