"""add recargo_mora to periodos_facturacion

Revision ID: dc96c568ffcc
Revises: 7ea1f452bdf0
Create Date: 2026-03-16 14:38:01.174773
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'dc96c568ffcc'
down_revision: Union[str, None] = '7ea1f452bdf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('facturas', 'numero_factura',
               existing_type=sa.VARCHAR(length=30),
               comment='Número de factura (ej: 6-21-2-2026)',
               existing_comment='Número consecutivo de factura (ej: VDR-2026-02-001)',
               existing_nullable=False)
    op.add_column('periodos_facturacion', sa.Column('recargo_mora', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False, comment='Recargo por mora cuando se supera la fecha de vencimiento'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('periodos_facturacion', 'recargo_mora')
    op.alter_column('facturas', 'numero_factura',
               existing_type=sa.VARCHAR(length=30),
               comment='Número consecutivo de factura (ej: VDR-2026-02-001)',
               existing_comment='Número de factura (ej: 6-21-2-2026)',
               existing_nullable=False)
    # ### end Alembic commands ###
