"""add_performance_indexes

Revision ID: 7ea1f452bdf0
Revises: 97e1821f0d5d
Create Date: 2026-03-14 12:59:55.597068
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '7ea1f452bdf0'
down_revision: Union[str, None] = '97e1821f0d5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_facturas_creado_en'), 'facturas', ['creado_en'], unique=False)
    op.create_index(op.f('ix_facturas_estado'), 'facturas', ['estado'], unique=False)
    op.create_index('ix_propowner_principal_activo', 'propiedad_propietarios', ['es_principal', 'fecha_fin'], unique=False)
    op.create_index(op.f('ix_propiedades_activo'), 'propiedades', ['activo'], unique=False)
    op.create_index(op.f('ix_propietarios_activo'), 'propietarios', ['activo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_propietarios_activo'), table_name='propietarios')
    op.drop_index(op.f('ix_propiedades_activo'), table_name='propiedades')
    op.drop_index('ix_propowner_principal_activo', table_name='propiedad_propietarios')
    op.drop_index(op.f('ix_facturas_estado'), table_name='facturas')
    op.drop_index(op.f('ix_facturas_creado_en'), table_name='facturas')
    # ### end Alembic commands ###
